apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name  : shippingservice-fault-injection
spec:
  hosts:
  - shippingservice
  http:
  - fault:
      delay:
        fixedDelay: .2s
        percent: 100
    match:
    - sourceLabels:
        app: frontend
    route:
    - destination:
        host: shippingservice

  - fault:
      delay:
        percent: 100
        fixedDelay: .2s
    match:
    - uri:
        regex: ".*/GetQuote"
    route:
    - destination:
        host: shippingservice

  - route:
    - destination:
        host: shippingservice  


